### ISSUE TITLE
Caching to speed to remote unwinding (UPT)

### ISSUE THREAD

**Issue by Jongy** [libunwind/libunwind#431] opened 2022-10-24 09:58 UTC
I am using libunwind (v1.6.2) to unwind a remote process. The flow in general is:
1. `unw_create_addr_space` with some modified accessors (to access a copy of the stack & registers for the thread, not the live stack)
2. Then `_UPT_create` on the PID
3. `unw_init_remote` with the address space object & upt object.

I get the stack & registers from a BPF program, and then do the unwinding in usermode. The underlying program is a profiler, and the unwinding appears to be very heavy and this limits the frequency I can use for the profiler.

I profiled the profiler itself, and saw that it spends lots of time (re)reading the `/proc/pid/maps` file (via `maps_next`) and even more time reading ELF images.
I wonder if libunwind supports any caching that could help here. We tried to cache the upt & address space objects per-PID, and to enable caching via `unw_set_caching_policy`, but it doesn't seem to help (i.e the maps files are always re-read, same for the ELF image). What I'd expect (or rather, the feature I want) is for libunwind to cache the `maps` per PID, and cache the unwinding info form ELF files it has read (again per PID), until I call `unw_flush_cache`. Was I using it incorrectly? Does this feature exist?

Thanks!

**Comment by fantasyzh** [comment] 2023-05-30 08:10
even worse if there are lots of threads in this process and want to do backtrace for each thread

**Comment by bregma** [comment] 2023-08-24 13:25
Closing as a duplicate of #15

**Closed by bregma** 2023-08-24 13:25 UTC
Labels: enhancement
