### ISSUE TITLE
libunwind QNX aarch64 lose some stack frame compared with QNX gdb

### ISSUE THREAD

**Issue by iDings** [libunwind/libunwind#603] opened 2023-08-24 13:42 UTC
QNX's bt_get_backtrace api is totally broken on aarch64, really glad to see that libunwind support QNX platform, thanks :+1: 

I encountered an issue on QNX aarch64 libunwind:
Problem: 
   when use libunwind nto api([example](https://gist.github.com/iDings/ab547a17cf4d153f58e7183115a74eaf)) to do remote unwind, the output seems success, but when compared with QNX's gdb output, found that an stack frame is losed. 
   90118 is syslogd's pid, 1 is tid of syslogd 
Case 1:
   libunwind's output:
   ```
    # pidin ar | grep syslogd
      90118 syslogd -f /system/etc/syslog.conf 

    # ./libunwind_example_remote 90118 1 
    0x2864a67cd0: (SignalWaitinfoMask+0x8)
    0x2864aa121c: (pselect+0x164)
    0x2864aa14e8: (select+0x48)
    0x1fded855b0: (main+0x2e0)
  ```
  use QNX's gdb remote attach and backtrace, output:
```
(gdb) target qnx 172.31.1.110:8000
Remote debugging using 172.31.1.110:8000
MsgNak received - resending
Remote target is little-endian
(gdb) attach 90118
Attaching to pid 90118 tid 1
[New pid 90118 tid 1]
[New pid 90118 tid 2]
[New pid 90118 tid 3]
[New pid 90118 tid 4]
[New pid 90118 tid 5]
SignalWaitinfoMask () at /builds/workspace/710-SDP/build_aarch64/lib/c/kercalls/aarch64/SignalWaitinfoMask.S:8
8       /builds/workspace/710-SDP/build_aarch64/lib/c/kercalls/aarch64/SignalWaitinfoMask.S: No such file or directory.
(gdb) bt
#0  SignalWaitinfoMask () at /builds/workspace/710-SDP/build_aarch64/lib/c/kercalls/aarch64/SignalWaitinfoMask.S:8
#1  0x0000002864aa0d08 in _poll (fds=fds@entry=0x54f0ccea50, nfds=0, fd_first=fd_first@entry=0, timo=<optimized out>, timo@entry=-1, extra_mask=extra_mask@entry=0, nebadfp=0x54f0cceb54, nebadfp@entry=0x54f0cceba4, sigmask=sigmask@entry=0x0) at /builds/workspace/710-SDP/build_aarch64/lib/c/xopen/poll.c:518
#2  0x0000002864aa121c in pselect (nfds=20, readfds=0x54f0ccec50, writefds=0x0, exceptfds=0x0, timeout=<optimized out>, sigmask=sigmask@entry=0x0) at /builds/workspace/710-SDP/build_aarch64/lib/c/xopen/poll.c:164
#3  0x0000002864aa14e8 in select (nfds=<optimized out>, readfds=<optimized out>, writefds=<optimized out>, exceptfds=<optimized out>, timeout=<optimized out>) at /builds/workspace/710-SDP/build_aarch64/lib/c/xopen/poll.c:105
#4  0x0000001fded855b0 in main (argc=<optimized out>, argv=<optimized out>) at /builds/workspace/710-SDP/build_aarch64/services/syslogd/syslogd.c:421
(gdb) 
```

Case 2:
unwind syslogd's thread 2
libunwind output:
 ```
# ./libunwind_example_remote 90118 2 
0x2864a6829c: (MsgReceive+0xc)
0x2864a5ec38: (_thread_pool_thread+0xc0)
0x2864a5f7c4: (thread_pool_start+0x54)
0x1fded85c58: (nto_main+0x168)
# 
```
gdb output:
  ```
(gdb) t 2
[Switching to thread 2 (pid 90118 tid 2)]
#0  MsgReceive () at /builds/workspace/710-SDP/build_aarch64/lib/c/kercalls/aarch64/MsgReceive.S:9
9       /builds/workspace/710-SDP/build_aarch64/lib/c/kercalls/aarch64/MsgReceive.S: No such file or directory.
(gdb) bt
#0  MsgReceive () at /builds/workspace/710-SDP/build_aarch64/lib/c/kercalls/aarch64/MsgReceive.S:9
#1  0x0000002864a5d0e4 in resmgr_block (ctp=0x43cf9a3210) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/resmgr.c:290
#2  0x0000002864a5ec38 in _thread_pool_thread (pool=pool@entry=0x43cf99c040, ctp=0x43cf9a3210) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/_thread_pool_thread.c:305
#3  0x0000002864a5eda4 in _thread_pool_context_thread (data=data@entry=0x43cf99c040) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/_thread_pool_thread.c:278
#4  0x0000002864a5f7c4 in thread_pool_start (tp=0x43cf99c040) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/thread_pool.c:96
#5  0x0000001fded85c58 in nto_main (x=<optimized out>) at /builds/workspace/710-SDP/build_aarch64/services/syslogd/syslogd.c:1516
#6  0x0000002864a48e00 in pthread_attr_setdetachstate (attr=0x43cf9a3218, detachstate=-811978056) at /builds/workspace/710-SDP/build_aarch64/lib/c/1c/pthread_attr_setdetachstate.c:30
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

from Case 1, ```0x0000002864aa0d08 in _poll``` frame is losed
from Case 2, ``` 0x0000002864a5d0e4 in resmgr_block``` and ```0x0000002864a5eda4 in _thread_pool_context_thread``` is losed,
and gdb's  ```0x0000002864a48e00 in pthread_attr_setdetachstate``` seems incorrect.

Anyway, 
 one lose case is that stack frame after syscall such as ```MsgReceive```, ```SignalWaitinfoMask```, for this case, enable libunwind's debug output ([tmux-0-5-0-20230824T211135.log](https://github.com/libunwind/libunwind/files/12429846/tmux-0-5-0-20230824T211135.log)), i found some infomation, 
![image](https://github.com/libunwind/libunwind/assets/2938288/b4100ce8-362a-40c8-939b-5c720b24f36e)
 dwarf unwind fail, and fallback to use fp guess, 
https://github.com/libunwind/libunwind/blob/90e3e53f0131f3410454d2550e50fc9763d0b025/src/aarch64/Gstep.c#L367-L383
i doubt QNX's syscall is handcrafted without CFI directives, and this make dwarf unwind failed and failback to fp? and syscall didn't use save fp, finally this will use the previous frame's fp, which will skip previous frame
![image](https://github.com/libunwind/libunwind/assets/2938288/017a2179-8e4d-43f2-9c4a-9669dd437e7f) 
for this case, use lr seems better, any method to judge this case and pass through to below procedure like ```is_plt_entry``` check
https://github.com/libunwind/libunwind/blob/90e3e53f0131f3410454d2550e50fc9763d0b025/src/aarch64/Gstep.c#L359
https://github.com/libunwind/libunwind/blob/90e3e53f0131f3410454d2550e50fc9763d0b025/src/aarch64/Gstep.c#L406-L414

And in Case 2, ```0x0000002864a5eda4 in _thread_pool_context_thread``` is also losed, from libunwind log, didn't found more fallback, seems not the same issue. [tmux-0-5-0-20230824T214047.log](https://github.com/libunwind/libunwind/files/12430033/tmux-0-5-0-20230824T214047.log), 

@bregma  look forward to get some suggestions from you
Many Thanks.

**Comment by bregma** [comment] 2023-08-24 14:55
> i doubt QNX's syscall is handcrafted without CFI directives, and this make dwarf unwind failed and failback to fp? and syscall didn't use save fp, finally this will use the previous frame's fp, which will skip previous frame

Yes, on aarch64 the kernel call code does not use `.cfi_` directives as it does on x86_64 so some frames get skipped. It might be possible to have a specialized kernel-call detection function during fallback: I can investigate.

I have no explanation for the missing `_thread_pool_context_thread()` unless there is some kind of optimization inlining going on.

**Comment by iDings** [comment] 2023-08-24 15:47
> Yes, on aarch64 the kernel call code does not use `.cfi_` directives as it does on x86_64 so some frames get skipped. It might be possible to have a specialized kernel-call detection function during fallback: I can investigate.

thanks.  look forward to your good news.

> I have no explanation for the missing `_thread_pool_context_thread()` unless there is some kind of optimization inlining going on.

i will check the disassemble code to see whether can find an clue to this missing stack frame.

**Comment by iDings** [comment] 2023-08-25 04:10
For "why ```_thread_pool_context_thread()``` is missing" issue
disassemble  ```_thread_pool_context_thread```,  compiler use ```b       0x4bc2c <_thread_pool_thread+180>``` to jump, seems to be an tail call optimization, callee will reusing the stack of the caller.  Still curious about how gdb unwind handle this, and whether if we can do the same in libunwind.
gdb have an tailcall unwinder: https://gitlab.collabora.com/vivek/binutils-gdb/-/blob/1e00bdd002750c14e64118fa4db20795d1e0f00a/gdb/dwarf2-frame-tailcall.c#L458
```asm
Dump of assembler code for function _thread_pool_thread:                                
   0x000000000004bb78 <+0>:     stp     x29, x30, [sp, #-128]!               
   0x000000000004bb7c <+4>:     adrp    x2, 0xc1000 <_select_query@got.plt>   
   0x000000000004bb80 <+8>:     mov     x29, sp       
   0x000000000004bb84 <+12>:    ldr     x2, [x2, #2816]              
   0x000000000004bb88 <+16>:    stp     x19, x20, [sp, #16]
   0x000000000004bb8c <+20>:    mov     x19, x0                          
   0x000000000004bb90 <+24>:    stp     x21, x22, [sp, #32]
   0x000000000004bb94 <+28>:    add     x0, sp, #0x48                                   
   0x000000000004bb98 <+32>:    mov     x22, x1                                    
   0x000000000004bb9c <+36>:    stp     x23, x24, [sp, #48]                        
   0x000000000004bba0 <+40>:    adrp    x1, 0x4b000 <dispatch_context_free+8>
   0x000000000004bba4 <+44>:    add     x1, x1, #0x898                                                                                                                           
   0x000000000004bba8 <+48>:    ldr     x3, [x2]                           
   0x000000000004bbac <+52>:    str     x3, [sp, #120]
   0x000000000004bbb0 <+56>:    mov     x3, #0x0                        // #0           
   0x000000000004bbb4 <+60>:    stp     x19, x22, [sp, #72]                                                                                                                      
   0x000000000004bbb8 <+64>:    mov     w23, #0x1                       // #1           
   0x000000000004bbbc <+68>:    str     wzr, [sp, #88]                   
   0x000000000004bbc0 <+72>:    stp     x1, x0, [sp, #104]               
   0x000000000004bbc4 <+76>:    bl      0x24f50 <__tls@plt>                      
   0x000000000004bbc8 <+80>:    mov     x24, x0                                         
   0x000000000004bbcc <+84>:    add     x0, sp, #0x60                                   
   0x000000000004bbd0 <+88>:    ldr     x21, [x19, #120]
   0x000000000004bbd4 <+92>:    ldr     x1, [x24, #72]
   0x000000000004bbd8 <+96>:    str     x0, [x24, #72]
   0x000000000004bbdc <+100>:   str     x1, [sp, #96]
   0x000000000004bbe0 <+104>:   b       0x4bc2c <_thread_pool_thread+180>
   0x000000000004bbe4 <+108>:   mov     x22, x20

```

**Comment by iDings** [comment] 2023-08-25 06:40
More about "why _thread_pool_context_thread() is missing" issue:
seems gdb also not track the all backtrace right, still take syslogd, use ```thread apply all bt``` to dump all threads backtrace.
 
Thread 5,4,3 seems also missing an backtrace frame between  ```_thread_pool_thread``` and ```pthread_attr_setdetachstate```,
openqnx have an old version QNX source code, for syslogd and dispatch's thread_pool, i think the code is almostly same with the QNX7.1.
From [dispatch/_thread_pool_thread.c#L211](https://github.com/vocho/openqnx/blob/cc95df3543a1c481d4f8ad387e29f0d1ff0c87fe/trunk/lib/c/dispatch/_thread_pool_thread.c#L211) and [dispatch/_thread_pool_thread.c#L93](https://github.com/vocho/openqnx/blob/cc95df3543a1c481d4f8ad387e29f0d1ff0c87fe/trunk/lib/c/dispatch/_thread_pool_thread.c#L93),  the caller of  ```_thread_pool_thread``` should be ```_thread_pool_context_thread```,  despite [_thread_pool_reserve_thread](https://github.com/vocho/openqnx/blob/cc95df3543a1c481d4f8ad387e29f0d1ff0c87fe/trunk/lib/c/dispatch/_thread_pool_thread.c#L182C7-L182C34) also call [_thread_pool_thread](https://github.com/vocho/openqnx/blob/cc95df3543a1c481d4f8ad387e29f0d1ff0c87fe/trunk/lib/c/dispatch/_thread_pool_thread.c#L192C13-L192C13), but i bet shouldn't run that flow.  Anyway, the caller of ```_thread_pool_thread``` shouldn't be ```pthread_attr_setdetachstate```.

```
(gdb) thread apply all bt                     

Thread 5 (pid 90118 tid 5):
#0  MsgReceive () at /builds/workspace/710-SDP/build_aarch64/lib/c/kercalls/aarch64/MsgReceive.S:9
#1  0x0000002864a5d0e4 in resmgr_block (ctp=0x43cf99c6d0) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/resmgr.c:290
#2  0x0000002864a5ec38 in _thread_pool_thread (pool=0x43cf99c040, ctp=0x43cf99c6d0) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/_thread_pool_thread.c:305
#3  0x0000002864a48e00 in pthread_attr_setdetachstate (attr=0x43cf99c6d8, detachstate=-812005512) at /builds/workspace/710-SDP/build_aarch64/lib/c/1c/pthread_attr_setdetachstate.c:30
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (pid 90118 tid 4):
#0  MsgReceive () at /builds/workspace/710-SDP/build_aarch64/lib/c/kercalls/aarch64/MsgReceive.S:9
#1  0x0000002864a5d0e4 in resmgr_block (ctp=0x43cf99cfc0) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/resmgr.c:290
#2  0x0000002864a5ec38 in _thread_pool_thread (pool=0x43cf99c040, ctp=0x43cf99cfc0) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/_thread_pool_thread.c:305
#3  0x0000002864a48e00 in pthread_attr_setdetachstate (attr=0x43cf99cfc8, detachstate=-812003224) at /builds/workspace/710-SDP/build_aarch64/lib/c/1c/pthread_attr_setdetachstate.c:30
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (pid 90118 tid 3):
#0  MsgReceive () at /builds/workspace/710-SDP/build_aarch64/lib/c/kercalls/aarch64/MsgReceive.S:9
#1  0x0000002864a5d0e4 in resmgr_block (ctp=0x43cf9a2920) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/resmgr.c:290
#2  0x0000002864a5ec38 in _thread_pool_thread (pool=0x43cf99c040, ctp=0x43cf9a2920) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/_thread_pool_thread.c:305
#3  0x0000002864a48e00 in pthread_attr_setdetachstate (attr=0x43cf9a2928, detachstate=-811980344) at /builds/workspace/710-SDP/build_aarch64/lib/c/1c/pthread_attr_setdetachstate.c:30
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (pid 90118 tid 2):
#0  MsgReceive () at /builds/workspace/710-SDP/build_aarch64/lib/c/kercalls/aarch64/MsgReceive.S:9
#1  0x0000002864a5d0e4 in resmgr_block (ctp=0x43cf9a3210) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/resmgr.c:290
#2  0x0000002864a5ec38 in _thread_pool_thread (pool=pool@entry=0x43cf99c040, ctp=0x43cf9a3210) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/_thread_pool_thread.c:305
#3  0x0000002864a5eda4 in _thread_pool_context_thread (data=data@entry=0x43cf99c040) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/_thread_pool_thread.c:278
#4  0x0000002864a5f7c4 in thread_pool_start (tp=0x43cf99c040) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/thread_pool.c:96
#5  0x0000001fded85c58 in nto_main (x=<optimized out>) at /builds/workspace/710-SDP/build_aarch64/services/syslogd/syslogd.c:1516
#6  0x0000002864a48e00 in pthread_attr_setdetachstate (attr=0x43cf9a3218, detachstate=-811978056) at /builds/workspace/710-SDP/build_aarch64/lib/c/1c/pthread_attr_setdetachstate.c:30
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (pid 90118 tid 1):
#0  SignalWaitinfoMask () at /builds/workspace/710-SDP/build_aarch64/lib/c/kercalls/aarch64/SignalWaitinfoMask.S:8
#1  0x0000002864aa0d08 in _poll (fds=fds@entry=0x54f0ccea50, nfds=0, fd_first=fd_first@entry=0, timo=<optimized out>, timo@entry=-1, extra_mask=extra_mask@entry=0, nebadfp=0x54f0cceb54, nebadfp@entry=0x54f0cceba4, sigmask=sigmask@entry=0x0) at /builds/workspace/710-SDP/build_aarch64/lib/c/xopen/poll.c:518
#2  0x0000002864aa121c in pselect (nfds=20, readfds=0x54f0ccec50, writefds=0x0, exceptfds=0x0, timeout=<optimized out>, sigmask=sigmask@entry=0x0) at /builds/workspace/710-SDP/build_aarch64/lib/c/xopen/poll.c:164
#3  0x0000002864aa14e8 in select (nfds=<optimized out>, readfds=<optimized out>, writefds=<optimized out>, exceptfds=<optimized out>, timeout=<optimized out>) at /builds/workspace/710-SDP/build_aarch64/lib/c/xopen/poll.c:105
#4  0x0000001fded855b0 in main (argc=<optimized out>, argv=<optimized out>) at /builds/workspace/710-SDP/build_aarch64/services/syslogd/syslogd.c:421
```

**Comment by iDings** [comment] 2023-08-25 06:54
Why gdb show the function of upmost call frame is ```pthread_attr_setdetachstate```
 From LR 0x0000000078085e00 show in gdb's backtrace, the LR point to ```__my_thread_exit```, gdb will minus an offset to LR to calculate the real calling pc, ```pthread_attr_setdetachstate``` is just on the above of ```__my_thread_exit```, cause the gdb show this incorrect proc name.
```__my_thread_exit``` is used by ```ThreadCreate_r``` in [pthread_create](https://github.com/vocho/openqnx/blob/cc95df3543a1c481d4f8ad387e29f0d1ff0c87fe/trunk/lib/c/1c/pthread_create.c#L30), QNX kernel seems will set the thread's final LR to this function.
 
```
(gdb) bt
#0  MsgReceive () at /builds/workspace/710-SDP/build_aarch64/lib/c/kercalls/aarch64/MsgReceive.S:9
#1  0x000000007809a0e4 in resmgr_block (ctp=0x110d2210) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/resmgr.c:290
#2  0x000000007809bc38 in _thread_pool_thread (pool=pool@entry=0x110cb040, ctp=0x110d2210) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/_thread_pool_thread.c:305
#3  0x000000007809bda4 in _thread_pool_context_thread (data=data@entry=0x110cb040) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/_thread_pool_thread.c:278
#4  0x000000007809c7c4 in thread_pool_start (tp=0x110cb040) at /builds/workspace/710-SDP/build_aarch64/lib/c/dispatch/thread_pool.c:96
#5  0x00000000100c2c58 in nto_main (x=<optimized out>) at /builds/workspace/710-SDP/build_aarch64/services/syslogd/syslogd.c:1516
#6  0x0000000078085e00 in pthread_attr_setdetachstate (attr=0x110d2218, detachstate=286073528) at /builds/workspace/710-SDP/build_aarch64/lib/c/1c/pthread_attr_setdetachstate.c:30
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) x/-2i 0x0000000078085e00
   0x78085df8 <pthread_attr_setdetachstate+32>: str     w2, [x3]
   0x78085dfc <pthread_attr_setdetachstate+36>: ret
(gdb) x/i 0x0000000078085e00
   0x78085e00 <__my_thread_exit>:       b       0x78073b30 <pthread_exit@plt>
```

**Comment by bregma** [comment] 2023-08-25 12:51
You have run into a (known) bug in QNX regarding thread stack unwinding on aarch64. The problem is because there is no userspace trampoline for thread entry, which works fine in C but makes proper unwinding impossible. It's particularly bad for C++ because it causes uncaught exceptions on any but the initial thread to enter an infinite loop.

There is nothing libunwind can do to fix that situation. It has been fixed in QNX 8 but QNX 7 was released 6 years ago and is not likely to get a thrreading redesign at this point. You will just have to live with this.

**Comment by iDings** [comment] 2023-08-25 15:08
> There is nothing libunwind can do to fix that situation. It has been fixed in QNX 8 but QNX 7 was released 6 years ago and is not likely to get a thrreading redesign at this point. You will just have to live with this.

sure, i can survive that :smile:


> disassemble `_thread_pool_context_thread`, compiler use `b 0x4bc2c <_thread_pool_thread+180>` to jump, seems to be an tail call optimization, callee will reusing the stack of the caller. Still curious about how gdb unwind handle this, and whether we can do the same in libunwind.

> seems gdb also not track the all backtrace right, still take syslogd, use `thread apply all bt` to dump all threads backtrace.
> 
> Thread 5,4,3 seems also missing an backtrace frame between `_thread_pool_thread` and `pthread_attr_setdetachstate`, openqnx have an old version QNX source code, for syslogd and dispatch's thread_pool, i think the code is almostly same with the QNX7.1.

Any suggestions about tail call optimization, gdb seems can't always unwind the TCO frame,  Thread 2 did, but Thread 5,4,5  didn't. For tail call optimization stack, is there any method to unwind?

**Comment by iDings** [comment] 2023-08-31 08:00
#607 try to fix lose caller frame of QNX aarch64 kernel call.

For tail call optimization, gdb seems use DW_TAG_call_site, and dwarf spec also have DW_AT_call_tail_call,  maybe too more work to support this on libunwind? 
> This functionality is currently supported only by DWARF 2 debugging format and the compiler has to produce ‘DW_TAG_call_site’ tags. 
https://sourceware.org/gdb/onlinedocs/gdb/Tail-Call-Frames.html

**Closed** 2023-09-04 13:32 UTC
