### ISSUE TITLE
Tests fail on Alpine Linux

### ISSUE THREAD

**Issue by ararslan** [libunwind/libunwind#75] opened 2018-04-12 01:12 UTC
I built libunwind master on Alpine Linux 3.7 x86-64 in Docker using
```sh
./autogen.sh
./configure
make
```
I then ran the test suite using `make check`, which produced the following summary:
```
PASS: test-proc-info
PASS: test-static-link
PASS: test-strerror
PASS: Gtest-bt
PASS: Ltest-bt
PASS: Gtest-exc
PASS: Ltest-exc
PASS: Gtest-init
PASS: Ltest-init
PASS: Gtest-concurrent
PASS: Ltest-concurrent
../config/test-driver: line 107:  1880 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: Gtest-resume-sig
../config/test-driver: line 107:  1904 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: Ltest-resume-sig
../config/test-driver: line 107:  1928 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: Gtest-resume-sig-rt
../config/test-driver: line 107:  1952 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: Ltest-resume-sig-rt
PASS: Gtest-trace
PASS: Ltest-trace
FAIL: Ltest-init-local-signal
PASS: Ltest-mem-validate
FAIL: test-async-sig
PASS: test-flush-cache
PASS: test-init-remote
PASS: test-mem
PASS: test-reg-state
PASS: Ltest-varargs
PASS: Ltest-nomalloc
PASS: Ltest-nocalloc
PASS: Lrs-race
PASS: test-ptrace
../config/test-driver: line 107:  2320 Aborted                 (core dumped) "$@" > $log_file 2>&1
FAIL: test-setjmp
FAIL: run-check-namespace
PASS: run-ptrace-mapper
PASS: run-ptrace-misc
FAIL: run-coredump-unwind
============================================================================
Testsuite summary for libunwind 1.3-rc1
============================================================================
# TOTAL: 34
# PASS:  25
# SKIP:  0
# XFAIL: 0
# FAIL:  9
# XPASS: 0
# ERROR: 0
```
The full log of configuration, building, and running the tests, as well as the `tests/test-suite.log` file are available in https://gist.github.com/ararslan/ca1efacb3f06426d1b4c1a399bd35735.

**Comment by ararslan** [comment] 2018-04-12 01:42
Perhaps worth noting that the host and target triplets are misidentified as `x86_64-pc-linux-gnu`, which I assume implies that it thinks the system is using glibc. `gcc -dumpmachine` calls the system `x86_64-alpine-linux-musl`, which appropriately reflects the system's libc.

**Comment by djwatson** [comment] 2018-04-12 16:48
Yea I think there are two issues:

1) Most of the tests don't pass except on gcc glibc x86-64.  Any fixes for other platforms/arches/ libc's are gladly accepted

2) config gets the wrong triplet sometimes.  Not sure what the root cause is, but probably related to #73 , #47

**Comment by djwatson** [comment] 2019-06-12 16:08
I think it is unlikely we will get all the tests to pass on all platforms, unfortunately.  Closing, but feel free to provide PRs for test fixes.

**Closed by djwatson** 2019-06-12 16:08 UTC
