### ISSUE TITLE
Symbols are not available after chroot

### ISSUE THREAD

**Issue by cmouse** [libunwind/libunwind#115] opened 2019-04-24 09:58 UTC
OS: Debian 9.0, 
libunwind-1.1-4.1

When trying to create backtrace inside chrooted process, libunwind fails to find symbols.

Simple reproduction:
```.c
#include <sys/types.h>
#include <stdio.h>
#include <unistd.h>
#include <libunwind.h>
#include <assert.h>

int backtrace()
{
	char proc_name[256];
	int ret;
	unsigned int fp = 0;
	unw_cursor_t c;
	unw_context_t ctx;
	unw_proc_info_t pip;

	if ((ret = unw_getcontext(&ctx)) != 0) {
		printf("unw_getcontext() failed: %d", ret);
		return -1;
	}
	if ((ret = unw_init_local(&c, &ctx)) != 0) {
		printf("unw_init_local() failed: %d", ret);
		return -1;
	}

	do {
		printf("#%d ", fp);
		if ((ret = unw_get_proc_info(&c, &pip)) != 0) {
			printf("[unw_get_proc_info_failed(): %d]", ret);
		} else if (pip.start_ip == 0 || pip.end_ip == 0) {
			printf("[no start/end information]");
		} else if ((ret = unw_get_proc_name(&c, proc_name, sizeof(proc_name), 0)) != 0 &&
			   ret != UNW_ENOMEM) {
			printf("[unw_get_proc_name() failed: %d]", ret);
		} else {
			proc_name[255] = '\0';
			printf("%s", proc_name);
			printf("[0x%08lx]", pip.start_ip);
		}
		printf("\n");
		fp++;
	} while ((ret = unw_step(&c)) > 0);

	return ret == 0 ? 0 : -1;
}

static void some_other_function(void)
{
	backtrace();
}

static void some_function(void)
{
	some_other_function();
}

int main(void)
{
/* must be existing directory owned by root */
	assert(chroot("/empty") == 0);
	assert(setgid(99) == 0);
	assert(setuid(99) == 0);
	some_function();
	return 0;
}
```

Expected result:
```
#0 backtrace[0x55f817c78a50]
#1 some_other_function[0x55f817c78c1c]
#2 some_function[0x55f817c78c2d]
#3 main[0x55f817c78c39]
#4 __libc_start_main[0x7fd94c09a1f0]
#5 _start[0x55f817c78920]
#6 [no start/end information]
```

Actual result:
```
#0 [unw_get_proc_name() failed: -1]
#1 [unw_get_proc_name() failed: -1]
#2 [unw_get_proc_name() failed: -1]
#3 [unw_get_proc_name() failed: -1]
#4 [unw_get_proc_name() failed: -1]
#5 [unw_get_proc_name() failed: -1]
#6 [no start/end information]
```

**Comment by djwatson** [comment] 2019-06-12 16:13
Does this machine use separate debug files, that aren't available in the chroot?

**Comment by cmouse** [comment] 2019-06-18 17:47
Hi. No, it does not. The standard linux backtrace() function works fine with chrooted process.

**Comment by bregma** [comment] 2023-06-30 20:03
Closing as not a bug. If you move or rename the symbol files after the process starts (and chroot() effectively does just that) it's not going to be able to find them. Same with any named file.

**Closed by bregma** 2023-06-30 20:03 UTC
