### ISSUE TITLE
Failed to build for mipsel-openwrt-linux-musl

### ISSUE THREAD

**Issue by zcchm** [libunwind/libunwind#336] opened 2022-03-10 13:23 UTC
I failed to build libunwind 1.6.2 for mips from x86_64 linux.

configure command is:
```bash
./configure CFLAGS=-fPIC CXXFLAGS=-fPIC --disable-shared --prefix=/third_lib/proto/lib_linuxmips_32_openwrt_mt7621 --host=mipsel-openwrt-linux-musl CC=/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/bin/mipsel-openwrt-linux-musl-gcc
```
But when I build it, I got errors:
```bash
Making all in src
make[1]: Entering directory '/third_lib/build/mips_32_openwrt_mt7621/libunwind-1.6.2/src'
make  all-am
make[2]: Entering directory '/third_lib/build/mips_32_openwrt_mt7621/libunwind-1.6.2/src'
depbase=`echo mips/getcontext.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../libtool  --tag=CC   --mode=compile /cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/bin/mipsel-openwrt-linux-musl-gcc -DHAVE_CONFIG_H -I. -I../include  -I../include -I../include/tdep-mips -I. -D_GNU_SOURCE -DNDEBUG -I../include -I../include/tdep-mips -I. -fPIC  -D_GNU_SOURCE -DNDEBUG -MT mips/getcontext.lo -MD -MP -MF $depbase.Tpo -c -o mips/getcontext.lo mips/getcontext.S &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  /cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/bin/mipsel-openwrt-linux-musl-gcc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-mips -I. -D_GNU_SOURCE -DNDEBUG -I../include -I../include/tdep-mips -I. -fPIC -D_GNU_SOURCE -DNDEBUG -MT mips/getcontext.lo -MD -MP -MF mips/.deps/getcontext.Tpo -c mips/getcontext.S -o mips/getcontext.o
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/sys/glibc-types.h: Assembler messages:
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/sys/glibc-types.h:7: Error: unrecognized opcode `typedef unsigned char __u_char'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/sys/glibc-types.h:8: Error: unrecognized opcode `typedef unsigned short int __u_short'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/sys/glibc-types.h:9: Error: unrecognized opcode `typedef unsigned int __u_int'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/sys/glibc-types.h:10: Error: unrecognized opcode `typedef unsigned long int __u_long'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/sys/glibc-types.h:13: Error: unrecognized opcode `typedef signed char __int8_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/sys/glibc-types.h:14: Error: unrecognized opcode `typedef unsigned char __uint8_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/sys/glibc-types.h:15: Error: unrecognized opcode `typedef signed short int __int16_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/sys/glibc-types.h:16: Error: unrecognized opcode `typedef unsigned short int __uint16_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/sys/glibc-types.h:17: Error: unrecognized opcode `typedef signed int __int32_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/sys/glibc-types.h:18: Error: unrecognized opcode `typedef unsigned int __uint32_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/sys/glibc-types.h:23: Error: unrecognized opcode `__extension__ typedef signed long long int __int64_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/sys/glibc-types.h:24: Error: unrecognized opcode `__extension__ typedef unsigned long long int __uint64_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/sys/glibc-types.h:29: Error: unrecognized opcode `typedef char*__caddr_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/alltypes.h:93: Error: unrecognized opcode `typedef unsigned int uintptr_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/alltypes.h:108: Error: unrecognized opcode `typedef int intptr_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/alltypes.h:124: Error: unrecognized opcode `typedef signed char int8_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/alltypes.h:129: Error: unrecognized opcode `typedef short int16_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/alltypes.h:134: Error: unrecognized opcode `typedef int int32_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/alltypes.h:139: Error: unrecognized opcode `typedef long long int64_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/alltypes.h:144: Error: unrecognized opcode `typedef long long intmax_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/alltypes.h:149: Error: unrecognized opcode `typedef unsigned char uint8_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/alltypes.h:154: Error: unrecognized opcode `typedef unsigned short uint16_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/alltypes.h:159: Error: unrecognized opcode `typedef unsigned int uint32_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/alltypes.h:164: Error: unrecognized opcode `typedef unsigned long long uint64_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/alltypes.h:174: Error: unrecognized opcode `typedef unsigned long long uintmax_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/stdint.h:22: Error: unrecognized opcode `typedef int8_t int_fast8_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/stdint.h:23: Error: unrecognized opcode `typedef int64_t int_fast64_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/stdint.h:25: Error: unrecognized opcode `typedef int8_t int_least8_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/stdint.h:26: Error: unrecognized opcode `typedef int16_t int_least16_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/stdint.h:27: Error: unrecognized opcode `typedef int32_t int_least32_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/stdint.h:28: Error: unrecognized opcode `typedef int64_t int_least64_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/stdint.h:30: Error: unrecognized opcode `typedef uint8_t uint_fast8_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/stdint.h:31: Error: unrecognized opcode `typedef uint64_t uint_fast64_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/stdint.h:33: Error: unrecognized opcode `typedef uint8_t uint_least8_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/stdint.h:34: Error: unrecognized opcode `typedef uint16_t uint_least16_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/stdint.h:35: Error: unrecognized opcode `typedef uint32_t uint_least32_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/stdint.h:36: Error: unrecognized opcode `typedef uint64_t uint_least64_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/stdint.h:1: Error: unrecognized opcode `typedef int32_t int_fast16_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/stdint.h:2: Error: unrecognized opcode `typedef int32_t int_fast32_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/stdint.h:3: Error: unrecognized opcode `typedef uint32_t uint_fast16_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/bits/stdint.h:4: Error: unrecognized opcode `typedef uint32_t uint_fast32_t'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/endian.h:25: Error: unrecognized opcode `static __inline uint16_t __bswap16(uint16_t __x)'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/endian.h:26: Error: junk at end of line, first unrecognized character is `{'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/endian.h:27: Error: unrecognized opcode `return __x<<8|__x>>8'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/endian.h:28: Error: junk at end of line, first unrecognized character is `}'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/endian.h:30: Error: unrecognized opcode `static __inline uint32_t __bswap32(uint32_t __x)'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/endian.h:31: Error: junk at end of line, first unrecognized character is `{'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/endian.h:32: Error: unrecognized opcode `return __x>>24|__x>>8&0xff00|__x<<8&0xff0000|__x<<24'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/endian.h:33: Error: junk at end of line, first unrecognized character is `}'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/endian.h:35: Error: unrecognized opcode `static __inline uint64_t __bswap64(uint64_t __x)'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/endian.h:36: Error: junk at end of line, first unrecognized character is `{'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/endian.h:37: Error: unrecognized opcode `return __bswap32(__x)+0ULL<<32|__bswap32(__x>>32)'
/cross_compilers/mips_32_openwrt_mt7621/staging_dir/toolchain-mipsel_24kec+dsp_gcc-7.3.0_musl/include/endian.h:38: Error: junk at end of line, first unrecognized character is `}'
Makefile:4091: recipe for target 'mips/getcontext.lo' failed
make[2]: *** [mips/getcontext.lo] Error 1
make[2]: Leaving directory '/third_lib/build/mips_32_openwrt_mt7621/libunwind-1.6.2/src'
Makefile:2320: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/third_lib/build/mips_32_openwrt_mt7621/libunwind-1.6.2/src'
Makefile:612: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

Could someone help me?

**Comment by nephen** [comment] 2022-08-12 09:37
I had the same problem, I was using the mipsel-linux-muslsf-cross compilation tool obtained from http://musl.cc/
```bash
libtool: compile:  /root/compile/mcm/mipsel-linux-muslsf-cross/bin/mipsel-linux-muslsf-gcc -DHAVE_CONFIG_H -I. -I../include -I../include -I../include/tdep-mips -I. -D_GNU_SOURCE -DNDEBUG -I../include -I../include/tdep-mips -I. -std=c11 -D_GNU_SOURCE -DNDEBUG -MT mips/getcontext.lo -MD -MP -MF mips/.deps/getcontext.Tpo -c mips/getcontext.S  -fPIC -DPIC -o mips/.libs/getcontext.o
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/bits/alltypes.h: Assembler messages:
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/bits/alltypes.h:119: Error: unrecognized opcode `typedef unsigned short uint16_t'
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/bits/alltypes.h:124: Error: unrecognized opcode `typedef unsigned int uint32_t'
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/bits/alltypes.h:129: Error: unrecognized opcode `typedef unsigned long long uint64_t'
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/endian.h:19: Error: unrecognized opcode `static __inline uint16_t __bswap16(uint16_t __x)'
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/endian.h:20: Error: junk at end of line, first unrecognized character is `{'
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/endian.h:21: Error: unrecognized opcode `return __x<<8|__x>>8'
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/endian.h:22: Error: junk at end of line, first unrecognized character is `}'
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/endian.h:24: Error: unrecognized opcode `static __inline uint32_t __bswap32(uint32_t __x)'
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/endian.h:25: Error: junk at end of line, first unrecognized character is `{'
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/endian.h:26: Error: unrecognized opcode `return __x>>24|__x>>8&0xff00|__x<<8&0xff0000|__x<<24'
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/endian.h:27: Error: junk at end of line, first unrecognized character is `}'
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/endian.h:29: Error: unrecognized opcode `static __inline uint64_t __bswap64(uint64_t __x)'
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/endian.h:30: Error: junk at end of line, first unrecognized character is `{'
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/endian.h:31: Error: unrecognized opcode `return __bswap32(__x)+0ULL<<32|__bswap32(__x>>32)'
/root/compile/mcm/mipsel-linux-muslsf-cross/mipsel-linux-muslsf/include/endian.h:32: Error: junk at end of line, first unrecognized character is `}'
make[2]: *** [mips/getcontext.lo] Error 1
make[2]: Leaving directory `/root/compile/libunwind/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/root/compile/libunwind/src'
make: *** [all-recursive] Error 1
```

**Comment by lancewb** [comment] 2023-06-15 03:00
also failed to build libunwind 1.7.0 for mipsel_24kc
configure command:
`./configure --host=mipsel-openwrt-linux --prefix=/tmp/libunwind CFLAGS="-march=24kc -O2" CC=mipsel-openwrt-linux-gcc AR=mipsel-openwrt-linux-ar`
errors context:
`/home/wdl/openwrt/mipsel_toolchain/include/sys/glibc-types.h: Assembler messages:
/home/wdl/openwrt/mipsel_toolchain/include/sys/glibc-types.h:7: Error: unrecognized opcode `typedef unsigned char __u_char'
/home/wdl/openwrt/mipsel_toolchain/include/sys/glibc-types.h:8: Error: unrecognized opcode `typedef unsigned short int __u_short'
/home/wdl/openwrt/mipsel_toolchain/include/sys/glibc-types.h:9: Error: unrecognized opcode `typedef unsigned int __u_int'
/home/wdl/openwrt/mipsel_toolchain/include/sys/glibc-types.h:10: Error: unrecognized opcode `typedef unsigned long int __u_long'
/home/wdl/openwrt/mipsel_toolchain/include/sys/glibc-types.h:13: Error: unrecognized opcode `typedef signed char __int8_t'
/home/wdl/openwrt/mipsel_toolchain/include/sys/glibc-types.h:14: Error: unrecognized opcode `typedef unsigned char __uint8_t'
/home/wdl/openwrt/mipsel_toolchain/include/sys/glibc-types.h:15: Error: unrecognized opcode `typedef signed short int __int16_t'
/home/wdl/openwrt/mipsel_toolchain/include/sys/glibc-types.h:16: Error: unrecognized opcode `typedef unsigned short int __uint16_t'
/home/wdl/openwrt/mipsel_toolchain/include/sys/glibc-types.h:17: Error: unrecognized opcode `typedef signed int __int32_t'
/home/wdl/openwrt/mipsel_toolchain/include/sys/glibc-types.h:18: Error: unrecognized opcode `typedef unsigned int __uint32_t'
/home/wdl/openwrt/mipsel_toolchain/include/sys/glibc-types.h:23: Error: unrecognized opcode `__extension__ typedef signed long long int __int64_t'
/home/wdl/openwrt/mipsel_toolchain/include/sys/glibc-types.h:24: Error: unrecognized opcode `__extension__ typedef unsigned long long int __uint64_t'
/home/wdl/openwrt/mipsel_toolchain/include/sys/glibc-types.h:29: Error: unrecognized opcode `typedef char*__caddr_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/alltypes.h:93: Error: unrecognized opcode `typedef unsigned int uintptr_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/alltypes.h:108: Error: unrecognized opcode `typedef int intptr_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/alltypes.h:124: Error: unrecognized opcode `typedef signed char int8_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/alltypes.h:129: Error: unrecognized opcode `typedef signed short int16_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/alltypes.h:134: Error: unrecognized opcode `typedef signed int int32_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/alltypes.h:139: Error: unrecognized opcode `typedef signed long long int64_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/alltypes.h:144: Error: unrecognized opcode `typedef signed long long intmax_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/alltypes.h:149: Error: unrecognized opcode `typedef unsigned char uint8_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/alltypes.h:154: Error: unrecognized opcode `typedef unsigned short uint16_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/alltypes.h:159: Error: unrecognized opcode `typedef unsigned int uint32_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/alltypes.h:164: Error: unrecognized opcode `typedef unsigned long long uint64_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/alltypes.h:174: Error: unrecognized opcode `typedef unsigned long long uintmax_t'
/home/wdl/openwrt/mipsel_toolchain/include/stdint.h:22: Error: unrecognized opcode `typedef int8_t int_fast8_t'
/home/wdl/openwrt/mipsel_toolchain/include/stdint.h:23: Error: unrecognized opcode `typedef int64_t int_fast64_t'
/home/wdl/openwrt/mipsel_toolchain/include/stdint.h:25: Error: unrecognized opcode `typedef int8_t int_least8_t'
/home/wdl/openwrt/mipsel_toolchain/include/stdint.h:26: Error: unrecognized opcode `typedef int16_t int_least16_t'
/home/wdl/openwrt/mipsel_toolchain/include/stdint.h:27: Error: unrecognized opcode `typedef int32_t int_least32_t'
/home/wdl/openwrt/mipsel_toolchain/include/stdint.h:28: Error: unrecognized opcode `typedef int64_t int_least64_t'
/home/wdl/openwrt/mipsel_toolchain/include/stdint.h:30: Error: unrecognized opcode `typedef uint8_t uint_fast8_t'
/home/wdl/openwrt/mipsel_toolchain/include/stdint.h:31: Error: unrecognized opcode `typedef uint64_t uint_fast64_t'
/home/wdl/openwrt/mipsel_toolchain/include/stdint.h:33: Error: unrecognized opcode `typedef uint8_t uint_least8_t'
/home/wdl/openwrt/mipsel_toolchain/include/stdint.h:34: Error: unrecognized opcode `typedef uint16_t uint_least16_t'
/home/wdl/openwrt/mipsel_toolchain/include/stdint.h:35: Error: unrecognized opcode `typedef uint32_t uint_least32_t'
/home/wdl/openwrt/mipsel_toolchain/include/stdint.h:36: Error: unrecognized opcode `typedef uint64_t uint_least64_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/stdint.h:1: Error: unrecognized opcode `typedef int32_t int_fast16_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/stdint.h:2: Error: unrecognized opcode `typedef int32_t int_fast32_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/stdint.h:3: Error: unrecognized opcode `typedef uint32_t uint_fast16_t'
/home/wdl/openwrt/mipsel_toolchain/include/bits/stdint.h:4: Error: unrecognized opcode `typedef uint32_t uint_fast32_t'
/home/wdl/openwrt/mipsel_toolchain/include/endian.h:25: Error: unrecognized opcode `static __inline uint16_t __bswap16(uint16_t __x)'
/home/wdl/openwrt/mipsel_toolchain/include/endian.h:26: Error: junk at end of line, first unrecognized character is `{'
/home/wdl/openwrt/mipsel_toolchain/include/endian.h:27: Error: unrecognized opcode `return __x<<8|__x>>8'
/home/wdl/openwrt/mipsel_toolchain/include/endian.h:28: Error: junk at end of line, first unrecognized character is `}'
/home/wdl/openwrt/mipsel_toolchain/include/endian.h:30: Error: unrecognized opcode `static __inline uint32_t __bswap32(uint32_t __x)'
/home/wdl/openwrt/mipsel_toolchain/include/endian.h:31: Error: junk at end of line, first unrecognized character is `{'
/home/wdl/openwrt/mipsel_toolchain/include/endian.h:32: Error: unrecognized opcode `return __x>>24|__x>>8&0xff00|__x<<8&0xff0000|__x<<24'
/home/wdl/openwrt/mipsel_toolchain/include/endian.h:33: Error: junk at end of line, first unrecognized character is `}'
/home/wdl/openwrt/mipsel_toolchain/include/endian.h:35: Error: unrecognized opcode `static __inline uint64_t __bswap64(uint64_t __x)'
/home/wdl/openwrt/mipsel_toolchain/include/endian.h:36: Error: junk at end of line, first unrecognized character is `{'
/home/wdl/openwrt/mipsel_toolchain/include/endian.h:37: Error: unrecognized opcode `return __bswap32(__x)+0ULL<<32|__bswap32(__x>>32)'
/home/wdl/openwrt/mipsel_toolchain/include/endian.h:38: Error: junk at end of line, first unrecognized character is `}'
make[2]: *** [mips/getcontext.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/wdl/openwrt/libunwind-1.70/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/wdl/openwrt/libunwind-1.70/src'
make: *** [all-recursive] Error 1
`

**Comment by bregma** [comment] 2023-06-15 10:35
Looks like the file <endian,h> is messed up in your cross-build sources.  It's got a whole bunch of C code not wrapped in a `#if  !defined(__ASSEMBLER__)` directive. The thing that's in common with these errors is they all rely on the musl libc, which supplies that header. I suspect a bug needs to be reported to that project.

**Comment by bregma** [comment] 2023-06-23 18:37
Confirmed the musl libc header <endian.h> is not appropriate for including in preprocessed assembly files.

Closing as a bug in third-party code and unfixable from this project.

**Closed by bregma** 2023-06-23 18:37 UTC
